# Generated by Django 5.1.4 on 2024-12-18 10:01

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_account_created_by'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
