# Generated by Django 5.1.4 on 2024-12-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_account_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'unique': ' Bu user nomi mavjud '}, help_text='Required. 150 characters or fewer.', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
